# Generated by Django 6.0.2 on 2026-02-14 06:40

import web.models.user
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(
                default="user/photos/default.png",
                upload_to=web.models.user.photo_upload_to,
            ),
        ),
    ]
