# Generated by Django 6.0.2 on 2026-05-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="input",
            field=models.TextField(max_length=50000),
        ),
    ]
